language: php

sudo: required

services:
  - docker

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

before_install:
  - composer self-update

install: composer update --prefer-dist $COMPOSER_FLAGS

script: composer run-script check

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push korchasa/composer2docker;
    fi
